# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n  
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_right
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_LOG_DEFAULT_LEVEL=1 -DCONFIG_ZMK_LOG_LEVEL_DBG=y -DCONFIG_USB_DRIVER_LOG_LEVEL=0 -DCONFIG_USB_CDC_ACM_LOG_LEVEL=0 -DCONFIG_KERNEL_LOG_LEVEL=0 -DCONFIG_LOG_BUFFER_SIZE=8192 -DCONFIG_ZMK_BATTERY_REPORTING=y -DCONFIG_ZMK_BATTERY_REPORT_INTERVAL=5 -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=5000
    artifact-name: totem-right-diag
  - board: seeeduino_xiao_ble
    shield: settings_reset
